export {HomePage} from "./home/home";
export {PrincipalPage} from "./principal/principal";
export {DescripcionPage} from "./descripcion/descripcion";
export {LoginPage} from "./login/login";
export {RegistroPage} from "./registro/registro";
export {TabsPage} from "./tabs/tabs";
export {HcarreraPage} from "./hcarrera/hcarrera";
export {HfinanciamientoPage} from "./hfinanciamiento/hfinanciamiento";
export {InicioPage} from "./inicio/inicio";
